#	.file	"hello.c"
#	.option nopic
#	.attribute arch, "rv32i2p1"
#	.attribute unaligned_access, 0
#	.attribute stack_align, 16
#.text
	.section	.data
	.align	2
str:
	.string	"Test test"

.text
	.align	2
	.globl	main
	.type	main, @function
main:
	addi	sp,sp,-16
	sw	ra,12(sp)
	sw	s0,8(sp)
	addi	s0,sp,16
#	lui	a5,%hi(str)
#	addi	a0,a5,%lo(str)
# should be able to just `la`
	la	a0, str
	call	puts
	li	a5,0
	mv	a0,a5
	lw	ra,12(sp)
	lw	s0,8(sp)
	addi	sp,sp,16
	jr	ra
#	.size	main, .-main
#	.ident	"GCC: (g2ee5e430018) 12.2.0"
